name: Build and Publish AMI

on:
   push:
      branches:
         - main
         - ore/ditto-image-builder
   workflow_dispatch:
      inputs:
         k8s_version:
            description: "Specify the Kubernetes version"
            required: false
            default: "1.27.15"
            options:
               - "1.27.15"
               - "1.28.15"
               - "1.30.10"
               - "1.31.4"

permissions:
  id-token: write   # This is crucial for OIDC authentication
  contents: read    # Allows reading repository contents

jobs:
   build-ami:
      name: Build and Publish AMI
      runs-on: ubuntu-latest
      env:
         AWS_REGION: "us-east-2"
         ACCOUNT_ID: "261908217831"
         ROLE: "image-builder-runner"
         AWS_OUTPUT: "json"

      steps:
         - name: Checkout repository
           uses: actions/checkout@v3


         - name: Set up AWS
           uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
           with:
              aws-region: ${{ env.AWS_REGION }}
              role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ env.ROLE }}"
              role-session-name: image-builder@build-cluster-api-images=${{ github.run_id }}
              role-duration-seconds: 3600

         - name: Setup Packer
           uses: hashicorp/setup-packer@main
           with:
             version: "latest"

         - name: Install Packer Amazon Plugin
           run: |
            packer plugins install github.com/hashicorp/amazon

         - name: Validate Packer template
           run: |
              packer init -upgrade ./images/capi/packer/config.pkr.hcl 
              make validate-ami-ubuntu-2404 

         - name: Build AMI
           env:
              AWS_PROFILE: ditto-prod-primary
           run: |
            ./images/capi/make_ami_public.sh \
            make build-ami-ubuntu-2404 \
              AWS_REGION=${{ env.AWS_REGION }}

         - name: Make AMI Public
           env:
             AWS_REGION: ${{ env.AWS_REGION }}
           run: |
              ./images/capi/make_ami_public.sh
            

